### ISSUE TITLE
导出翻译报错

### ISSUE THREAD

**Issue by Smile8848** [NEKOparapa/AiNiee#128]
Success:  翻译阶段已完成，正在处理数据-----------------------------------

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "AiNiee4.py", line 6211, in run
  File "AiNiee4.py", line 289, in Main
  File "AiNiee4.py", line 6136, in output_translated_content
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 205, in _deepcopy_list
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 230, in _deepcopy_dict
  File "copy.py", line 161, in deepcopy
TypeError: cannot pickle '_io.TextIOWrapper' object
[INFO]  已选择输出文件夹: C:/Output/AiNiee4.62/杂
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "AiNiee4.py", line 6239, in run
  File "AiNiee4.py", line 6136, in output_translated_content
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 205, in _deepcopy_list
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 230, in _deepcopy_dict
  File "copy.py", line 161, in deepcopy
TypeError: cannot pickle '_io.TextIOWrapper' object

不知道啥原因

**Comment by NEKOparapa** [comment]
用测试版，修复了

**Comment by Smile8848** [comment]
> 用测试版，修复了

Error: 进行请求时出现问题！！！错误信息如下
Error: Connection error.

测试版报这个，但测试的时候是通的

[INFO] 已成功接受到AI的回复
[INFO] AI回复的文本内容：
 宝贝，我在想念你呢，你在干嘛呢？


[INFO] 全部API KEY测试结果--------------
第1个 API KEY：sk-xxxx测试结果：成功
[INFO] 所有API KEY测试成功！！！

**Comment by NEKOparapa** [comment]
你得看看你的翻译平台设置对了没

**Comment by NEKOparapa** [comment]
你把日志复制多些

**Comment by Smile8848** [comment]
> 你得看看你的翻译平台设置对了没

抱歉，我蠢了，平台变成chat官方，正常跑起来了。
