### ISSUE TITLE
关于gpt-4o-mini

### ISSUE THREAD

**Issue by nekomiya-hinata** [NEKOparapa/AiNiee#226]
使用`OpenAI官方`，在模型选择手动填入新的4o模型`gpt-4o-mini`
直接点测试请求没有报错，但在开始翻译时出现下面的错误：
```log
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "AiNiee.py", line 3268, in run
  File "AiNiee.py", line 127, in Main
  File "Module_Folders\Request_Limiter\Request_limit.py", line 52, in initialize_limiter
KeyError: 'gpt-4o-mini'
```

**Comment by NEKOparapa** [comment]
这个功能需要自行补充平台配置文件

**Comment by windknat** [comment]
<<用ChatGPT填入的配置，提供各位參考...

打開.json文件 (...\Resource\platform\openai.json)

付费账号{}裡面填入
"gpt-4o-mini": {"max_tokens": 4000, "TPM": 300000, "RPM": 500}
model_price{}裡面填入
"gpt-4o-mini": {"input_price": 0.0015, "output_price": 0.006}

**Comment by nekomiya-hinata** [comment]
才注意到还可以这样配置，谢谢
