### ISSUE TITLE
使用 gemini-1.5-pro-exp-0801 模型报错

### ISSUE THREAD

**Issue by jeshs** [NEKOparapa/AiNiee#238]
1、测试key正常
2、翻译时报错

Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Programs\miniconda3\envs\ainiee\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "D:\Code\AiNiee\AiNiee.py", line 3334, in run
    Translator.Main(self)
  File "D:\Code\AiNiee\AiNiee.py", line 126, in Main
    configurator.configure_translation_platform(configurator.translation_platform)  # 配置翻译平台信息
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\AiNiee\Module_Folders\Configurator\Config.py", line 387, in configure_translation_platform
    self.model_input_price = self.google_platform_config["model_price"][self.model_type]["input_price"]
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'gemini-1.5-pro-exp-0801'

**Comment by NEKOparapa** [comment]
https://github.com/NEKOparapa/AiNiee/issues/226
