### ISSUE TITLE
翻译完成后有个报错

### ISSUE THREAD

**Issue by wjh191** [NEKOparapa/AiNiee#26]
[1;33mWarning:[0m 当前OpenAI温度设置为： 0.8
[1;33mWarning:[0m 当剩下20句未翻译时，将进行逐行翻译-----------------------------------
[1;32mSuccess:[0m  翻译阶段已完成，正在处理数据-----------------------------------
[1;32mSuccess:[0m  原文与译文文件合并完成-----------------------------------
[1;32mSuccess:[0m  文本转化简中完成-----------------------------------
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "AiNiee-chatgpt4.py", line 183, in run
  File "AiNiee-chatgpt4.py", line 2142, in Main
  File "AiNiee-chatgpt4.py", line 836, in fill_empty_cells_with_values
IndexError: tuple index out of range

**Comment by NEKOparapa** [comment]
看问题是在检查整数数据时出错了，把原文文件发一下，还有如果有备份文件，也发一下

**Comment by NEKOparapa** [comment]
你的表格文件是转化过来的不是t++导出的，你应该在表格文件的第一行使用固定的表头，就是标有原文译文这些，具体看t++导出的表格文件。
