### ISSUE TITLE
近几天的版本运行报错

### ISSUE THREAD

**Issue by jeshs** [NEKOparapa/AiNiee#265]
翻译文本是英文，第三方类openai，游戏是Renpy，从t++导出的文本
运行时，报错
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\Programs\miniconda3\envs\ainiee\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "D:\Code\AiNiee\AiNiee.py", line 3507, in run
    Translator.Main(self)
  File "D:\Code\AiNiee\AiNiee.py", line 110, in Main
    plugin_manager.broadcast_event("preproces_text", configurator,configurator.cache_list)
  File "D:\Code\AiNiee\Plugin_Scripts\Plugin_Manager.py", line 21, in broadcast_event
    plugin.on_event(event_name, configuration_information, event_data)
  File "D:\Code\AiNiee\Plugin_Scripts\General_Text_Filtering_Plugin\General_Text_Filtering.py", line 20, in on_event
    self.filter_text(event_data)
  File "D:\Code\AiNiee\Plugin_Scripts\General_Text_Filtering_Plugin\General_Text_Filtering.py", line 54, in filter_text
    if source_text.endswith('.mp3') or source_text.endswith('.wav') or source_text.endswith('.png') or source_text.endswith('.jpg'):
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'endswith'
```
翻译原文件如下：
[game.zip](https://github.com/user-attachments/files/17140894/game.zip)

**Comment by jeshs** [comment]
还有个问题，添加代理平台，输入名字后，点击“确定”按钮没有反应，无法添加成功

**Comment by NEKOparapa** [comment]
从t++导出的文本报错应该是文本中有数值型数字，最近改动了过滤方法，所以出现这个问题，一会会修复。添加代理平台无翻译。。。这有点模糊，先重启一下软件试试，换不同名字看看，我后面再看看代码排查一下。

**Comment by jeshs** [comment]
添加代理平台重启试过也不行。
git更新代码后，启动会提示缺失依赖。
```
[INFO]  General_Text_Filtering_Plugin loaded!
Traceback (most recent call last):
  File "D:\Code\AiNiee\AiNiee.py", line 3645, in <module>
    plugin_manager.load_plugins_from_directory(configurator.plugin_dir)
  File "D:\Code\AiNiee\Plugin_Scripts\Plugin_Manager.py", line 37, in load_plugins_from_directory
    module = importlib.import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\miniconda3\envs\ainiee\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Code\AiNiee\Plugin_Scripts\MTool_Optimizer\MTool_Optimizer.py", line 4, in <module>
    from rich import print
ModuleNotFoundError: No module named 'rich'
```
