### ISSUE TITLE
开始翻译报错

### ISSUE THREAD

**Issue by jeshs** [NEKOparapa/AiNiee#267]
1. 翻译日文游戏报错，从t++导出
```
[INFO]  Text has been routinely filtered
Exception in thread Thread-6:
Traceback (most recent call last):
  File "D:\Programs\miniconda3\envs\ainiee\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "D:\Code\AiNiee\AiNiee.py", line 3507, in run
    Translator.Main(self)
  File "D:\Code\AiNiee\AiNiee.py", line 110, in Main
    plugin_manager.broadcast_event("preproces_text", configurator,configurator.cache_list)
  File "D:\Code\AiNiee\Plugin_Scripts\Plugin_Manager.py", line 21, in broadcast_event
    plugin.on_event(event_name, configuration_information, event_data)
  File "D:\Code\AiNiee\Plugin_Scripts\Non_Japanese_Korean_Text_Filtering_Plugin\Non_Japanese_Korean_Text_Filtering.py", line 24, in on_event
    self.process_dictionary_list(event_data)
  File "D:\Code\AiNiee\Plugin_Scripts\Non_Japanese_Korean_Text_Filtering_Plugin\Non_Japanese_Korean_Text_Filtering.py", line 39, in process_dictionary_list
    if source_text and not contains_cjk(source_text):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\AiNiee\Plugin_Scripts\Non_Japanese_Korean_Text_Filtering_Plugin\Non_Japanese_Korean_Text_Filtering.py", line 34, in contains_cjk
    return bool(pattern.search(text))
                ^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'int'
```
2. 原文件
[data.zip](https://github.com/user-attachments/files/17165013/data.zip)

**Comment by NEKOparapa** [comment]
测试版修了
