### ISSUE TITLE
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。

### ISSUE THREAD

**Issue by colin4k** [NEKOparapa/AiNiee#392]
[GlossaryChecker] 指令词典检查已完成 ...
[GlossaryChecker] 检查结果已写入 D:/Soft/AiNiee/book/指令词典检查_结果.json 文件，请检查结果并进行手工修正 ...

Exception in thread Thread-7 (translation_start_target):
Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "Module_Folders\Translator\Translator.py", line 288, in translation_start_target
  File "Module_Folders\File_Outputer\File2.py", line 1168, in output_translated_content
  File "Module_Folders\File_Outputer\File2.py", line 919, in output_epub_file
  File "shutil.py", line 460, in copy2
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。

看了下指令词典检查_结果.json，是空的。

**Comment by colin4k** [comment]
第二次又尝试用管理员权限启动，结果还是同样的错误，看起来是因为不同线程操作同一个文件引起的

**Comment by NEKOparapa** [comment]
是有程序一直打开这小说吧

**Comment by colin4k** [comment]
> 是有程序一直打开这小说吧

没有啊，就只开了 AiNiee 应用

**Comment by colin4k** [comment]
另外能否支持断点续跑功能，现在出错了重新开始又只能从头开始翻译

**Comment by NEKOparapa** [comment]
是支持断点续跑功能，GitHub有说明

**Comment by NEKOparapa** [comment]
你直接重启跑

**Comment by NEKOparapa** [comment]
重启你的电脑

**Comment by colin4k** [comment]
> 重启你的电脑

重启了，而且把缓存文件复制到其他目录，项目设置里面指向新目录，但还是报错：
[LanguageFilter] 开始执行预处理 ...

100%|██████████████████████████████████████████████████████████████████████████████████████████| 85/85 [00:00<?, ?it/s]

[LanguageFilter] 语言过滤已完成，共过滤 85 个不包含目标语言的条目 ...


[INFO] 所有文本均已翻译，翻译任务已结束 ...


[PunctuationFixer] 开始执行后处理 ...

100%|███████████████████████████████████████████████████████████████████████████| 5800/5800 [00:00<00:00, 34154.13it/s]

[PunctuationFixer] 标点修复已完成，已修复 1115 个标点错误的条目 ...

Exception in thread Thread-5 (translation_start_target):
Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "Module_Folders\Translator\Translator.py", line 288, in translation_start_target
  File "Module_Folders\File_Outputer\File2.py", line 1168, in output_translated_content
  File "Module_Folders\File_Outputer\File2.py", line 919, in output_epub_file
  File "shutil.py", line 460, in copy2
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。

**Comment by NEKOparapa** [comment]
你原文文件打包发出来

**Comment by colin4k** [comment]
> 你原文文件打包发出来

稍等我换个文件试试

**Comment by colin4k** [comment]
> 你原文文件打包发出来

换了个文件还是一样的错误，你试试我上传的这个
[The History Of The Orient Unveiled (Matthew S Cox, J R Rain).epub.zip](https://github.com/user-attachments/files/18243702/The.History.Of.The.Orient.Unveiled.Matthew.S.Cox.J.R.Rain.epub.zip)

**Comment by colin4k** [comment]
> 你原文文件打包发出来

哈哈，知道为什么了，我把输入和输出目录设置成同一个了，所以自然会占用。。。犯了个低级错误。。。

**Comment by colin4k** [comment]
换个不同的目录就好了，但是奇怪的是输出的文件名和原文件名也不相同啊

**Comment by NEKOparapa** [comment]
。。。。
