### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yjk47** [NEKOparapa/AiNiee#394]
[LanguageFilter] 开始执行预处理 ...

100%|█████████████████████████████████████████████████████████████████████████| 5395/5395 [00:00<00:00, 3425930.37it/s]

[LanguageFilter] 语言过滤已完成，共过滤 5395 个不包含目标语言的条目 ...

生成翻译任务:  99%|████████████████████████████████████████████████████████████████▎| 697/705 [00:01<00:00, 619.67it/s]
Exception in thread Thread-6 (translation_start_target):
Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "Module_Folders\Translator\Translator.py", line 238, in translation_start_target
  File "Module_Folders\Translator\TranslatorTask.py", line 244, in prepare
  File "Module_Folders\Translator\TranslatorTask.py", line 403, in generate_prompt
  File "Module_Folders\PromptBuilder.py", line 101, in build_translation_sample
  File "Module_Folders\PromptBuilder.py", line 371, in build_adaptive_translation_sample
  File "Module_Folders\PromptBuilder.py", line 257, in replace_and_increment
IndexError: list index out of range

**Comment by NEKOparapa** [comment]
更新到最新版

**Comment by yjk47** [comment]
[ERROR] 翻译任务错误 ... Error code: 418 - {'error_msg': 'Authentication Fails. Multiple 401 errors detected. Please
wait for 1 minute before trying again.'}
